name: fact_checker
description: Minimal Flutter app scaffold for FactChecker UI
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  file_picker: ^8.0.3

flutter:
  uses-material-design: true


